language: python
sudo: required
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install --quiet codecov wheel

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
